### ISSUE TITLE
User defined config not loading

### ISSUE THREAD

**Issue by bobthebutcher** [bobthebutcher/grifter#79]
For some reason the user defined config is not being loaded and results in errors.

```
grifter create guests.yml 
Traceback (most recent call last):
  File "/usr/local/bin/grifter", line 11, in <module>
    load_entry_point('grifter==0.2.11', 'console_scripts', 'grifter')()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/grifter/cli.py", line 139, in create
    validated_guest_data = validate_guest_data(guest_data, guest_config)
  File "/usr/local/lib/python3.6/site-packages/grifter/cli.py", line 68, in validate_guest_data
    validate_guest_interfaces(merged_data, config, interface_mappings)
  File "/usr/local/lib/python3.6/site-packages/grifter/validators.py", line 121, in validate_guest_interfaces
    if not int_map[remote_box]['data_interfaces'].get(remote_port):
KeyError: 'cisco/vmanage'
```

**Comment by bobthebutcher** [comment]
I think this is actually related to #80

**Comment by bobthebutcher** [comment]
Scratch that, not related to 80

**Comment by bobthebutcher** [comment]
The `generate_guest_interface_mappings` function is using the default config:
https://github.com/bobthebutcher/grifter/blob/5a37c17878d74cc8cf44ef69abaefd9d9b144c9c/grifter/api.py#L123

Rather than using the `merge_user_config` function 

https://github.com/bobthebutcher/grifter/blob/5a37c17878d74cc8cf44ef69abaefd9d9b144c9c/grifter/api.py#L196
